### ISSUE TITLE
Will you be able to continue maintenance of yamllint in the future?

### ISSUE THREAD

**Issue by kenchan0130** [shortdudey123/yamllint#38]
Hi.

This library is very useful for me.
But it seems that it is not maintained.

Will you be able to continue maintenance of yamllint in the future?

**Comment by imajes** [comment]
@shortdudey123 -- curious to what you think here. I don't think there's much active maintenance to do, but addressing deprecs etc seems advisable.

**Comment by shortdudey123** [comment]
I am reviewing current PR's and will try to keep things updated as PR's come in

closing . . .
